### ISSUE TITLE
design pattern  and framework choices

### ISSUE THREAD

**Issue by gvelez17** [trustgraph/trustgraph-rust-cli#5]
do we like these design principles? https://clig.dev/

**Comment by gvelez17** [comment]
clig for patterns high level

https://docs.rs/dialoguer/latest/dialoguer/ maybe as a library in rust

**Comment by gvelez17** [comment]
also which framework: https://github.com/clap-rs/clap. tua search crates.io for cli ?  maybe not dialoguer

**Comment by gvelez17** [comment]
http://fengsp.github.io/cli/cli/

**Comment by gvelez17** [comment]
https://blog.logrocket.com/rust-and-tui-building-a-command-line-interface-in-rust/
https://github.com/fdehau/tui-rs

**Comment by gvelez17** [comment]
not tua

**Comment by gvelez17** [comment]
i vote for https://docs.rs/clap/latest/clap/

**Comment by harlantwood** [comment]
Using clap :) 
Closing.
